version: '3.1'

volumes:
  postgres-data-vol: {}

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: enquete
    volumes:
      - postgres-data-vol:/var/lib/postgresql/data